services:
  web:
    image: ghcr.io/thoknu/devops-exam-project-thoknu:latest
    environment:
      ConnectionStrings__DefaultConnection: "Host=mariadb;Port=3306;Database=taskking;Username=taskking;Password=taskking"
    ports:
      - "8000:8080"
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - app-net

  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskking
      MYSQL_USER: taskking
      MYSQL_PASSWORD: taskking
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      - app-net

volumes:
  mariadb_data:

networks:
  app-net: