services:
  web:
    image: ghcr.io/thoknu/devops-exam-project-thoknu:latest
    environment:
      ConnectionStrings__DefaultConnection: "Host=mariadb;Port=3306;Database=taskking;Username=taskking;Password=taskking"
    ports:
      - "80:8080"
    depends_on:
      - mariadb
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskking
      MYSQL_USER: taskking
      MYSQL_PASSWORD: taskking
    restart: unless-stopped

  flyway:
    image: flyway/flyway:latest
    command:
      -url=jdbc:mariadb://mariadb:3306/taskking
      -user=taskking
      -password=taskking
      -locations=filesystem:/flyway/sql
      migrate
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - mariadb
    restart: "no"

volumes:
  mariadb_data: