services:
  web:
    image: ghcr.io/thoknu/devops-exam-project-thoknu:${VERSION}
    ports:
      - "80:8080"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskking
      MYSQL_USER: taskking
      MYSQL_PASSWORD: taskking

  flyway:
    image: flyway/flyway:latest
    depends_on:
      - mariadb
    volumes:
      - ./db/migrations:/flyway/sql
    command: migrate
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/taskking
      FLYWAY_USER: taskking
      FLYWAY_PASSWORD: taskking
    restart: "no"

volumes:
  mariadb_data: