name: Task King CI

on:
  push:
    branches:
      - dev
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.semver.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build

      - name: Application version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: true


  deploy_staging:
    needs: build_test
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u thoknu --password-stdin

      - name: Build image (staging)
        run: |
          docker build \
            -t ghcr.io/thoknu/devops-exam-project-thoknu:staging \
            -f server/TaskKing.Api/Dockerfile \
            server

      - name: Push image
        run: docker push ghcr.io/thoknu/devops-exam-project-thoknu:staging

      - name: Copy compose + migrations to staging
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          source: "compose.staging.yaml,db/migrations/V1__init.sql"
          target: app/

      - name: Deploy to staging
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          script: |
            cd app

            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u thoknu --password-stdin

            docker compose -f compose.staging.yaml pull
            docker compose -f compose.staging.yaml up -d --force-recreate --remove-orphans

      - name: Run k6 test (GET tasks)
        run: |
          docker run --rm -i \
            -e BASE_URL=http://${{ secrets.STAGING_SERVER_IP }}:8000 \
            grafana/k6 run - < k6/get-tasks-test.js


  deploy_prod:
    needs: build_test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u thoknu --password-stdin

      - name: Build image (prod)
        run: |
          docker build \
            -t ghcr.io/thoknu/devops-exam-project-thoknu:latest \
            -f server/TaskKing.Api/Dockerfile \
            server

      - name: Push image
        run: docker push ghcr.io/thoknu/devops-exam-project-thoknu:latest

      - name: Copy compose + migrations to production
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          source: "compose.prod.yaml,db/migrations/V1__init.sql"
          target: app/

      - name: Deploy to production
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            cd app

            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u thoknu --password-stdin

            docker compose -f compose.prod.yaml pull
            docker compose -f compose.prod.yaml up -d --force-recreate --remove-orphans