name: Task King CI

on:
  push:
    branches:
      - dev
      - main

jobs:
  build_test:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.semver.outputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
        
      - name: Install tools
        run: |
          dotnet tool install -g dotnet-sonarscanner
          dotnet tool install -g dotnet-reportgenerator-globaltool
          dotnet tool install -g dotnet-stryker

      - name: Start Static Code Analysis
        run: |
          dotnet sonarscanner begin \
            /k:"${{ secrets.SONARQUBE_PROJECT_KEY }}" \
            /d:sonar.host.url="${{ secrets.SONARQUBE_URL }}" \
            /d:sonar.token="${{ secrets.SONARQUBE_TOKEN }}" \
            /d:sonar.coverageReportPaths="coverage-report/SonarQube.xml" \
            /d:sonar.qualitygate.wait=true \
            /d:sonar.qualitygate.timeout=300 \
            /d:sonar.coverage.exclusions=**/Program.cs,**/Controllers/*.cs,**/TaskKing.E2E/**,**/k6/**
      
      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory TestResults

      - name: Generate coverage report
        run: |
          reportgenerator \
          -reports:"TestResults/**/coverage.cobertura.xml" \
          -targetdir:coverage-report \
          -reporttypes:SonarQube

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage-report

      - name: Run Mutation Tests
        run: dotnet stryker --config-file stryker-config.json --break-at 80
        
      - name: Upload Stryker Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stryker-report
          path: StrykerOutput/**/reports
      
      - name: Complete Static Code Analysis
        if: always()
        run: |
          dotnet sonarscanner end \
            /d:sonar.token="${{ secrets.SONARQUBE_TOKEN }}"
      
      - name: Application version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: true


  deploy_staging:
    needs: build_test
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u thoknu --password-stdin

      - name: Build image (staging)
        run: |
          docker build \
            -t ghcr.io/thoknu/devops-exam-project-thoknu:staging \
            -f server/TaskKing.Api/Dockerfile \
            server

      - name: Push image
        run: docker push ghcr.io/thoknu/devops-exam-project-thoknu:staging

      - name: Copy compose + migrations to staging
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          source: "compose.staging.yaml,db/migrations"
          target: app/

      - name: Deploy to staging
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_SERVER_USERNAME }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          script: |
            cd app

            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u thoknu --password-stdin

            docker compose -f compose.staging.yaml down
            docker compose -f compose.staging.yaml pull
            docker compose -f compose.staging.yaml up -d --force-recreate --remove-orphans
            
            echo "Waiting for API..."
            for i in {1..30}; do
            if curl -fs http://localhost:8000/api/tasks >/dev/null; then
            echo "API ready"
            exit 0
            fi
            sleep 2
            done
        
            echo "API never became ready"
            docker logs app-web-1 --tail 200
            exit 1

      - name: Run E2E tests (TestCafe)
        run: |
          cd TaskKing.E2E
          npm ci
          npx testcafe "chrome:headless --no-sandbox --disable-dev-shm-usage" tests/ui.e2e.js
        env:
          BASE_URL: http://${{ secrets.STAGING_SERVER_IP }}:8000

      - name: Run k6 test (GET tasks)
        if: success()
        run: |
          docker run --rm -i \
            -e BASE_URL=http://${{ secrets.STAGING_SERVER_IP }}:8000 \
            grafana/k6 run - < k6/get-tasks-test.js


  deploy_prod:
    needs: build_test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u thoknu --password-stdin

      - name: Build image (prod)
        run: |
          docker build \
            -t ghcr.io/thoknu/devops-exam-project-thoknu:latest \
            -f server/TaskKing.Api/Dockerfile \
            server

      - name: Push image
        run: docker push ghcr.io/thoknu/devops-exam-project-thoknu:latest

      - name: Copy compose + migrations to production
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          source: "compose.prod.yaml,db/migrations"
          target: app/

      - name: Deploy to production
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            cd app

            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u thoknu --password-stdin

            docker compose -f compose.prod.yaml down
            docker compose -f compose.prod.yaml pull
            docker compose -f compose.prod.yaml up -d --force-recreate --remove-orphans